### ISSUE TITLE
빌드하는 방법을 등록해주면 좋겠구나.

### ISSUE THREAD

**Issue by yongwoo2** [hataeho1/QuizApp#6]

**Comment by hataeho1** [comment]
빌드하는 방법
---
1. Git Clone or Pull
2. Pom.xml 파일에서 마우스 우측 클릭후 Run As > Maven Build
3. Goals 입력란에 `eclipse:clean eclipse:eclipse` 입력후 빌드
4. 맥 상단 메뉴바에서 Project > Clean 한번 실행 (만약을 위해서)
5. 프로젝트 루트를 선택후 오른쪽 클릭 > 새로코침 한번 실행 (만약을 위해서)
6. `org.univ7.webapp.quiz` 패키지 내에 `QuizAppApplication.java` 파일을 한번 클릭<br>
      > 오른쪽 클릭 > Run AS > Java Application

프로그램 내 테스트 계정 정보
---
로그인 아이디 : user
로그인 pw : pw

**Comment by yongwoo2** [comment]
@hataeho1 
잘 안되네.
낼 학교 오면 나한데 잠시 들리렴.
